### ISSUE TITLE
README correct link for MEGNet paper

### ISSUE THREAD

**Issue by Irratzo** [AlexDuvalinho/geometric-gnns#3]
The current link to the MEGNet paper in the README model table is https://reader.elsevier.com/reader/sd/pii/S1053811921006777. With Firefox browser, following this link leads to the error "Secure Connection Failed", with Chrome browser "This site can’t provide a secure connection". Using the identifier in the email and searching with Elsevier leads to the URL https://www.sciencedirect.com/science/article/pii/S1053811921006777, referencing the paper "MEGnet: Automatic ICA-based artifact removal for MEG using spatiotemporal convolutional neural networks" from 2021. I think this is the wrong paper. The correct preprint that the table *should* point to here is probably https://arxiv.org/abs/1812.05055, "Graph Networks as a Universal Machine Learning Framework for Molecules and Crystals" by Chi Chen, ..., Shyue Ping Ong, from 2018. So, the year in the table would also have to be corrected from 2019 to 2018. Thank you.

Disclaimer. I am not affiliated with this work.

**Comment by AlexDuvalinho** [comment]
Thanks for letting us know !
